# Test
sudo: required
language: c++
compiler: gcc
env:
    - BUILDTYPE=cmake-make
    - BUILDTYPE=cmake-ninja
    - BUILDTYPE=autotools
services:
    - docker
install:
    - sudo docker --version
    - sudo docker build -f util/ci/arch-docker -t arch-gnucashbuild
    - sudo docker build -f util/ci/ubuntu-14.04-docker -t ubuntu-14.04-gnucashbuild
script:
    - sudo docker run --env="BUILDTYPE=$BUILDTYPE" --rm arch-gnucashbuild
    - sudo docker run --env="BUILDTYPE=$BUILDTYPE" --rm ubuntu-14.04-gnucashbuild
