# Test
sudo: required
language: c++
compiler: gcc
env:
    - BUILDTYPE=cmake-make
    - BUILDTYPE=cmake-ninja
    - BUILDTYPE=autotools
services:
    - docker
install:
    - sudo docker --version
    - sudo docker build . -t gnucashbuild
script:
    - sudo docker run --env="BUILDTYPE=$BUILDTYPE" --rm gnucashbuild
